name: Build and Analyze
on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: "tests${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  test-results-check-name: Test results

jobs:
  unit-tests-run:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Switch Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_14.2.app"
      - name: Collect Workflow Telemetry
        uses: AlexPerathoner/workflow-telemetry-action@v0.9
        with:
          metric_frequency_thousands_of_second: 100
      - name: get pods home directory from cache
        uses: actions/cache@v1
        with:
          path: ./iGlance/cocoaPodsHomeDir
          key: ${{ runner.os }}--pods-homeDir-key-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}--pods-homeDir-key-
      - name: get installed pods from cache
        uses: actions/cache@v1
        with:
          path: ./iGlance/Pods
          key: ${{ runner.os }}--pods-key-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}--pods-key-
      - name: execute 'pod install' 
        working-directory: ./iGlance
        run: pod install
        env:
          CP_HOME_DIR: ./cocoaPodsHomeDir
      # update carthage
      - name: execute 'carthage update'
        working-directory: ./iGlance/iGlance
        run: carthage update
      - name: Build and Test
        continue-on-error: true
        id: run-tests
        working-directory: ./iGlance
        run: |
          xcodebuild clean test \
          -workspace iGlance.xcworkspace \
          -scheme iGlanceUITests \
          -destination platform=macOS \
          -resultBundlePath TestResults \
          -test-iterations 10 \
          CODE_SIGNING_ALLOWED=NO || exit 1